export const MOBILE_SIDEBAR_ACTIVE_X_TRANSLATION = '0'
export const MOBILE_SIDEBAR_INACTIVE_X_TRANSLATION = '-400px'

export const MOBILE_SIDEBAR_ACTIVE_Y_TRANSLATION = '0'
export const MOBILE_SIDEBAR_PREVIEW_Y_TRANSLATION = 'calc(100vh - 170px)'
export const MOBILE_SIDEBAR_INACTIVE_Y_TRANSLATION = '100vh'

export const MOBILE_BUTTONS_INACTIVE_Y_TRANSLATION = '0'
export const MOBILE_BUTTONS_PREVIEW_Y_TRANSLATION = '-170px'
